apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bot
  labels:
    app: bot
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bot
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
