apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bot
  name: bot
spec:
  selector:
    matchLabels:
      app: bot
  replicas: 1
  template:
    metadata:
      labels:
        app: bot
    spec:
      automountServiceAccountToken: true
      serviceAccount: bot-sa
      containers:
      - name: master
        image: k3d-quake-registry:5000/bot:latest
